### ISSUE TITLE
403 error on user details by id endpoint

### ISSUE THREAD

**Issue by westcorperations** [Rishikant181/Rettiwt-API#780]
### Environment

linux

### Reproduction

     const rettiwt = new Rettiwt({ apiKey: token });
await rettiwt.user.details(userId);

### Description

TWITTER_ERROR: Request failed with status code 403 @Rishikant181 

### Logs

```shell-script

```

**Comment by Bruce-zxy** [comment]
same.

<img width="900" height="420" alt="Image" src="https://github.com/user-attachments/assets/62874721-425c-4c0c-95e4-ba852db64630" />

**Comment by Rishikant181** [comment]
Did the account get suspended?

**Comment by Bruce-zxy** [comment]
> Did the account get suspended?

No, the `details` function doesn't throw a 403 error if the `username` parameter is passed. It only throws a 403 error if no parameter is passed or if the user's ID is passed.

I discovered this problem today; I could access it normally a few days ago, which is very strange. @Rishikant181

**Comment by westcorperations** [comment]
> > Did the account get suspended?
> 
> No, the `details` function doesn't throw a 403 error if the `username` parameter is passed. It only throws a 403 error if no parameter is passed or if the user's ID is passed.
> 
> I discovered this problem today; I could access it normally a few days ago, which is very strange. [@Rishikant181](https://github.com/Rishikant181)

@Rishikant181 exactly my case also username works but id doesnt

**Comment by Rishikant181** [comment]
@Bruce-zxy I asked about suspension because I reproduced the issue, then got an account suspension email 30 minutes or so after that. So I thought it might have been the issue (although, it might have been because of the fact that I was experimenting sending DMs from this library yesterday using that same account, and that account has been used for experimentation since the day Rettiwt-API was published lol).

**Comment by westcorperations** [comment]
> [@Bruce-zxy](https://github.com/Bruce-zxy) I asked about suspension because I reproduced the issue, then got an account suspension email 30 minutes or so after that. So I thought it might have been the issue (although, it might have been because of the fact that I was experimenting sending DMs from this library yesterday using that same account, and that account has been used for experimentation since the day Rettiwt-API was published lol).

 My account isnt suspended @Rishikant181

**Comment by Rishikant181** [comment]
@westcorperations That's a relief. I was really worried that it was causing suspensions.

**Comment by Bruce-zxy** [comment]
> [@Bruce-zxy](https://github.com/Bruce-zxy)我询问账号被封禁的原因是因为我重现了这个问题，然后大约30分钟后就收到了账号被封禁的邮件。所以我认为这可能是问题所在（虽然，也可能是因为我昨天用同一个账号尝试从这个库发送私信，而且自从Rettiwt-API发布以来，这个账号就一直用于实验，哈哈）。

My account wasn't banned either; I even just liked Elon Musk's tweet on the privacy tab. @Rishikant181

**Comment by Bruce-zxy** [comment]
@westcorperations @Rishikant181 This is a bit strange. The problem disappeared after I upgraded the library to version 6.0.7. I'm not sure if it was because reinstalling the library and upgrading the version solved the problem, because I don't remember my original version number. You can try it.

**Comment by westcorperations** [comment]
Still getting the error on the 6.0.7 @Bruce-zxy

**Comment by Rishikant181** [comment]
I only encountered error 403 but it was because of my account suspension. With another of my active account, I have not been able to reproduce this issue (I tested on `6.0.7`).

**Comment by Bruce-zxy** [comment]
@westcorperations This is very puzzling. Are you using a proxy? Or have you deleted node_modules and reinstalled it completely?

**Comment by arjun-go-go** [comment]
<img width="1856" height="429" alt="Image" src="https://github.com/user-attachments/assets/e724891c-7a3c-46ee-89e2-8f17cad15e94" />

**Comment by arjun-go-go** [comment]
> [@westcorperations](https://github.com/westcorperations)这非常令人费解。你是否使用了代理？或者你是否删除了 node_modules 文件夹并完全重新安装了它？


403 error on user details by id     UserByRestId

**Comment by westcorperations** [comment]
> [@westcorperations](https://github.com/westcorperations) This is very puzzling. Are you using a proxy? Or have you deleted node_modules and reinstalled it completely?

no i am not using proxy and i ahve delete the node_modules and reinstalled @Bruce-zxy @Rishikant181

**Comment by westcorperations** [comment]
i  close
 the issue
by mistake @Rishikant181 please reopen

**Comment by westcorperations** [comment]
<img width="341" height="192" alt="Image" src="https://github.com/user-attachments/assets/5e38c8b3-c385-419e-8c9e-7a74002bb377" />

<img width="341" height="192" alt="Image" src="https://github.com/user-attachments/assets/ac611d61-3f2d-4520-ad47-9020fce15fa6" /> still getting it @Rishikant181

**Comment by Rishikant181** [comment]
@westcorperations Can try using your own browser's user agent as a custom header  to Rettiwt?

Set the header as follows:

```ts
const rettiwt = new Rettiwt({ apiKey: "<API_KEY>", headers: { 'User-Agent': "<YOUR_BROWSERS_USER_AGENT>" } });
```

Use this to get your user agent: https://dnschecker.org/user-agent-info.php

**Comment by westcorperations** [comment]
didnt work @Rishikant181

**Comment by westcorperations** [comment]
had to find my way around this i reversed
 the endpoint that get users connect account list on x the map with my x id to get object of user details i need

**Comment by emraherkol** [comment]
I get a 431 error when I try to get the details of multiple users in bulk.

**Comment by Bruce-zxy** [comment]
@westcorperations You can print the config log on line 238 of node_modules/rettiwt-api/dist/services/public/FetcherService.js, see what the output is, and then paste it here. Maybe we can see together what the problem is.

**Comment by Bruce-zxy** [comment]
> I get a 431 error when I try to get the details of multiple users in bulk.

@emraherkol status-code 431 means your request body is too large, and the server rejected your request. You can try querying in batches.

**Comment by Rishikant181** [comment]
@emraherkol How many users are you trying to fetch at once? If it's over 200, that might be reason.

**Comment by emraherkol** [comment]
@Bruce-zxy @Rishikant181 Wow. It was giving error 431 with 320 user IDs. When I split it into 200s, it worked fine. Thank you.

**Comment by Rishikant181** [comment]
@emraherkol The bulk user details endpoint has a limit at 220 users per request. However, I personally go with 200.

**Comment by dschwertfeger** [comment]
I have the same issue.

My Logs indicate this started 3 days ago, which aligns with when the issue was opened. I tried both suggestions:

- [x] Upgraded from `v6.0.5` to `v6.0.7` → issue persists
- [x] Reduced batch size (even to 100) → issue persists

The `tweet.details` endpoint works without issues just as before.

Any other ideas?

**Comment by Rishikant181** [comment]
@dschwertfeger In your case, is it the bulk details that's not working, or the details of a single tweet by ID?

**Comment by dschwertfeger** [comment]
I wondered the same and did a few more tests.

Note that this is not about ~~`tweet.details`~~ but `user.details`:

- Single user by id `user.details(id)` → `403`
- Bulk users by ids `user.details(ids)` → `403`

…even with a brand new account (so it certainly isn't suspended.)

Single user by user name `user.details(username)`, which only needs guest access, works fine, but doesn't scale.

Again, `tweet.details` don't seem to be affected and continue to work as usual.

**Comment by SakuraKoi** [comment]
Banned TLS fingerprint, or user-agent with tls fingerprint mismatch, that's it, at least 4 me

**Comment by dnefi** [comment]
> Banned TLS fingerprint, or user-agent with tls fingerprint mismatch, that's it, at least 4 me

Do you have more information on how to resolve this?

**Comment by Rishikant181** [comment]
If the `User-Agent` is really the issue, then using the `User-Agent` string of the host making the request might fix that. It can be done using the `headers` option while configuring `Rettiwt`.

In that case, a fix might be to use an API call to get user agent for current host making the request, then using that user agent string for outgoing requests.

@dschwertfeger @westcorperations Can you try using the `User-Agent` of the host machine where you're making the request from and confirm if that's really the case?

**Comment by dschwertfeger** [comment]
I couldn't see why the `User-Agent` would be the issue, considering that only `user.details()` started returning `403`'s while `tweet.details()` continues to work fine…

But I tried overriding the `User-Agent` anyway.

Still get the `403` though.

**Comment by Rishikant181** [comment]
@dschwertfeger So that rules out `User-Agent`. The blocker on this issue is that I still haven't been able to reproduce this issue at all.

**Comment by Rishikant181** [comment]
@dschwertfeger I have another hypothesis: since the `User-Agent` header, as well as the proxy does not get passed on to the `x-client-transaction-id` generator library, that mismatch might be what's triggering the 403 errors.

I was going to add proxy support  to the said library anyways, so I'll just include the headers too and push out a patch, and we'll see.

**Comment by dschwertfeger** [comment]
Oooh, that sounds promising… and also more likely to cause a mismatch than simply setting the `User-Agent` header.

Ping me when you have the patch. I'm happy to try it and provide feedback.

**Comment by SakuraKoi** [comment]
> > Banned TLS fingerprint, or user-agent with tls fingerprint mismatch, that's it, at least 4 me
> 
> Do you have more information on how to resolve this?

spoof your [tls fingerprint](https://fingerprint.com/blog/what-is-tls-fingerprinting-transport-layer-security/), mimic it as a browser, not nodejs, then set a user agent that matches your tls fingerprint.

they only applied this check to `UserByRestId` endpoint.

you can verify by capture the http packet and replay with Node.js: send the exact same http packet and see browser returning 200 but nodejs got a 403. or just setup a nodejs based MITM proxy and use it on your browser, then you'll found even browser is failing.

a few months ago they banned java, now it's nodejs, at least that's how it appears to me. analyzing this took me a long time. everything magically back working when I tried packet capture with MITM(as my MITM is not banned), but it failing again when i'm not capturing them, what a heck of ghost detection. i eventually confirmed that it had nothing to do with http, but rather something lower-level.

**Comment by Rishikant181** [comment]
@dschwertfeger @westcorperations I've pushed out `v6.0.8`. Please try it and let me know (I still wasn't able to reproduce the issue so I don't really know if that patch should have fixed it).

**Comment by dschwertfeger** [comment]
Thanks for the patch, @Rishikant181. I updated to `v6.0.8`, set a custom `User-Agent`, but still get a `403`.

And looking at the `diff`, I'm not surprised. 

The `403` comes directly from Cloudflare. So, presumably, the request never even reaches the X servers.

Here's the `err.response.data` from `FetcherService`:

<details>

<summary>Click to open</summary>

```html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> x.com</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
    <p class="text-13">
      <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">9a01103b9e6c321c</strong></span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
      <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
        Your IP:
        <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
        <span class="hidden" id="cf-footer-ip">***.**.***.**</span> <!-- Redacted -->
        <span class="cf-footer-separator sm:hidden">&bull;</span>
      </span>
      <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
      
    </p>
    <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
  </div><!-- /.error-footer -->

    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script>
    window._cf_translation = {};
    
    
  </script>
</body>
```

</details>

Basically, just like the screenshot @arjun-go-go posted in https://github.com/Rishikant181/Rettiwt-API/issues/780#issuecomment-3501848995.

I understand it's difficult for you to suggest a solution or next steps, since you can't even reproduce this, but I'm curious what you think about @SakuraKoi's suggestion about mimicking the TLS fingerprint?

It seems plausible. But at the same time, it's strange that you don't have issues with this endpoint. I'd assume that your fingerprint would also mismatch…

What's your take?

Would you suggest trying this approach? If so, how? Is this something that would need to be patched in `rettiwt`? Could this be done outside of it? Are there any special 3rd-party libraries for this?

I understand the idea in principle, but I wouldn't know how to implement it effectively, what tools and libraries to use, etc.

Any hints, ideas, pointers would be greatly appreciated. ✌️

**Comment by dnefi** [comment]
@dschwertfeger With the suggestion of @sakurakoi; I used mitmproxy and when I used the Twitter Mobile User-Agent the problem seems to be solved.

**Comment by SakuraKoi** [comment]
> [@dschwertfeger](https://github.com/dschwertfeger) With the suggestion of [@SakuraKoi](https://github.com/SakuraKoi); I used mitmproxy and when I used the Twitter Mobile User-Agent the problem seems to be solved.

this is unreliable. it works with mitmproxy only because they haven't banned mitmproxy's fingerprint **yet**. you should mimic a real browser's fingerprint, they never ban a real browser :)

**Comment by Rishikant181** [comment]
I think I found the reason for the 403s - it's Cloudflare's protection. I recently saw this while browsing X and it briefly popped up, suggesting that the same might also be case for `Rettiwt-API`.

Using a proxy server like [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) should solve the issue. I'm testing it out.
